spring:
  application:
    name: samapiece-backend
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: ${SERVER_PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never

samapiece:
  jwt:
    secret: ${JWT_SECRET}
  photo:
    cle-chiffrement: ${PHOTO_CLE_CHIFFREMENT}
